[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Pasqal-Quantum-Engineer-Use-Case"
authors = [{name = "Antoine Cornillot", email = "antoine.cornillot@student-cs.fr"}]
dynamic = ["version", "description"]
